version: '3'

services:
  db:
    image: mariadb:10.3
    command: ["--default-authentication-plugin=mysql_native_password --max_allowed_packet=134217728 "]
    ports:
        - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ssomoc
      MYSQL_USER: ssomoc
      MYSQL_PASSWORD: ssomoc

  php:
    build: ./docker/php
    image: ssomoc-php:latest
    depends_on:
      - db
    volumes:
      - ./app:/var/www

  nginx:
    build: ./docker/nginx
    image: ssomoc-nginx:latest
    volumes:
      - ./app:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    ports:
      - "80:80"
      - "443:443"


