version: '3'

services:
  siam:
      build: ./docker/siam
      image: siamoc:latest
      working_dir: /var/www
      volumes:
          - ./docker/siam:/var/www
          - ./docker/siam:/bindmount:rw
      ports:
          - "1234:1234"
  php:
    build: ./docker/php
    image: base-php:latest
    volumes:
      - ./app:/var/www:cached

  nginx:
    build: ./docker/nginx
    image: base-nginx:latest
    volumes:
      - ./app:/var/www:cached
      - ./logs/nginx:/var/log/nginx:cached
    ports: [80:80, 443:443]

  db:
    build: ./docker/db
    image: base-db:latest
    environment:
      POSTGRES_USER: ssomoc
      POSTGRES_PASSWORD: ssomoc
      POSTGRES_DB: ssomoc
    ports: [2345:5432]
    restart: always


