version: '3'

services:

  php:
    build: ./docker/php
    image: base-php:latest
    volumes:
      - ./app:/var/www
      - ./docker/php/xdebug.ini:/etc/php7/conf.d/xdebug.ini

  nginx:
    build: ./docker/nginx
    image: base-nginx:latest
    volumes:
      - ./app:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    ports: [80:80, 443:443]

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: ssomoc
      POSTGRES_PASSWORD: ssomoc
      POSTGRES_DB: ssomoc
    ports: [2345:5432]


