knpu_oauth2_client:
    clients:
        siam_client:
            type: generic
            provider_class: App\Service\Siam\Security\SiamProvider
            provider_options:
                baseAuthorizationUrl: '%env(SIAM_BASE_AUTHORIZATION_URL)%'
                baseAccessTokenUrl: '%env(SIAM_BASE_ACCESS_TOKEN_URL)%'
                resourceOwnerDetailsUrl: '%env(SIAM_RESOURCE_OWNER_DETAILS_URL)%'
            client_id: '%env(SIAM_CLIENT_ID)%'
            client_secret: '%env(SIAM_CLIENT_SECRET)%'
            redirect_route: 'api_siam_check'
        github:
            type: github
            client_id: '%env(GITHUB_CLIENT_ID)%'
            client_secret: '%env(GITHUB_CLIENT_SECRET)%'
            redirect_route: 'api_github_check'
            redirect_params: { }
