security:
    providers:
        memory_user_provider:
            memory:
                users:
                    'ssomoc@mail.com': { password: 'ssomoc', roles: [ 'ROLE_USER' ] }
        login_form_user_provider:
            id: App\Security\LoginFormUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: memory_user_provider
            guard:
                authenticators:
                    - App\Service\Siam\Security\SiamAuthenticator
                    - App\Security\Authenticator\LoginFormAuthenticator
                    - App\Security\Authenticator\TokenAuthenticator
                    - App\Security\Authenticator\GithubAuthenticator
                entry_point: App\Security\Authenticator\TokenAuthenticator
            stateless: true
            logout:
                path: app_logout

    access_control:
        - { path: ^/api/github/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/oauth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
